DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS loader CASCADE;
DROP TABLE IF EXISTS jobs CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS loader_jobs CASCADE;

CREATE TABLE users (
    id SERIAL PRIMARY KEY NOT NULL,
    login VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    permissions VARCHAR NOT NULL
);

CREATE TABLE customer (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id SERIAL NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    capital INTEGER NOT NULL
);

CREATE TABLE loader (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id SERIAL NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    max_portable_weight INTEGER NOT NULL,
    fatigue INTEGER NOT NULL,
    salary INTEGER NOT NULL,
    drunkenness SMALLINT NOT NULL
);

CREATE TABLE jobs (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id SERIAL NOT NULL REFERENCES customer (id) ON DELETE CASCADE,
    name VARCHAR NOT NULL,
    cargo_weight INTEGER NOT NULL
);

CREATE TABLE sessions (
    user_id SERIAL NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    refreshToken VARCHAR DEFAULT '',
    expires timestamp NOT NULL
);

CREATE TABLE loader_jobs (
    loader_id SERIAL NOT NULL REFERENCES loader (id) ON DELETE CASCADE,
    job_id SERIAL NOT NULL REFERENCES jobs (id) ON DELETE CASCADE
);