DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS loader CASCADE;
DROP TABLE IF EXISTS jobs CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS loader_jobs CASCADE;